SELECT *
FROM users
WHERE USERNAME = 'pikachu'
;

SELECT *
FROM POSTS
WHERE REGISTRATION_DATE BETWEEN TO_DATE ('2023-01-01', 'YYYY-MM-DD')
          AND TO_DATE ('2023-12-31', 'YYYY-MM-DD')
;

SELECT USERNAME, email
FROM USERS
WHERE USER_ID IN (1,2,3,4,5,6,7,8)
;

SELECT post_id, content
FROM POSTS
WHERE CONTENT LIKE '%#먹스타그램%'
;

SELECT *
FROM POSTS
WHERE USER_ID = 1 AND POST_TYPE = 'photo'
;

SELECT user_id, username
FROM USERS
WHERE USER_ID NOT BETWEEN 9 AND 20
;